/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_qinan_MathData */

#ifndef _Included_com_qinan_MathData
#define _Included_com_qinan_MathData
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_qinan_MathData
 * Method:    degreeByCircle
 * Signature: (FFFFFF)F
 */
JNIEXPORT jfloat JNICALL Java_com_qinan_MathData_degreeByCircle
  (JNIEnv *, jclass, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat);

#ifdef __cplusplus
}
#endif
#endif
